[package]
name = "bf_inter"
version = "0.1.0"
authors = ["Andreas Ejdesgaard <andreasejdesgaard@protonmail.com>"]
edition = "2018"

[profile.release]

[dependencies]
libc = "0.2.67"
structopt = "0.3.11"
clap = { git = "https://github.com/clap-rs/clap/" }
